# Generated by Django 2.2.6 on 2019-10-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=75)),
                ('blog', models.URLField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
